export const QUERY_KEYS = { 
    POST_MEMBERS_CHECKNICKNAME : ['POST_MEMBERS_CHECKNICKNAME'],
    POST_MEMBERS_SIGNUP : ['POST_MEMBERS_SIGNUP'],
    POST_DOGS_PROFILE : ['POST_DOGS_PROFILE'],
    GET_PLACES_INFO: "GET_PLACES_INFO",
} as const;
