export const QUERY_KEYS = { 
    POST_MEMBERS_CHECKNICKNAME : ['POST_MEMBERS_CHECKNICKNAME'],
    POST_MEMBERS_SIGNUP : ['POST_MEMBERS_SIGNUP'],
    GET_MEMBERS_INFO : ['GET_MEMBERS_INFO'],
    POST_DOGS_PROFILE : ['POST_DOGS_PROFILE'],
    GET_DOGS_PROFILES : ['GET_DOGS_PROFILES'],
    GET_PLACES_INFO: "GET_PLACES_INFO",
} as const;
