name: Build
on:
  push:
    branches:
      - develop #빌드하고싶은 브랜치
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.5.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4.5.1
        run: corepack prepare yarn@4.5.1 --activate

      - name: Yarn Install
        run: |
          yarn install

      - name: Create .env file
        run: |
          echo "VITE_BASE_URL=${{secrets.VITE_BASE_URL}}" >> .env
          echo "VITE_KAKAO_MAP=${{secrets.VITE_KAKAO_MAP}}" >> .env
          echo "VITE_NAVER_OCR_INVOKE_URL=${{secrets.VITE_OCR}}" >> .env
          echo "VITE_NAVER_X_OCR_SECRET=${{secrets.VITE_OCR_SECRET}}" >> .env

      - name: Yarn Build
        run: |
          yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME2 }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY2 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY2 }}
          AWS_REGION: ${{secrets.AWS_REGION}}
          SOURCE_DIR: "dist"
